# The purpose of this workflow file is to make sure the app
# builds successfully as well as to check whether it passes
# the linter and the tests

name: Setup Builds and Tests

on:
  push:
    branches: [main, deploy]
  pull_request:
    branches: [main, deploy]

jobs:
  linux-setup-and-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm update
      - run: npm run lint
      - run: npm run build:prod:web
      - run: npm run test
    # - run: npm test -- "--karma-config=./tests/karma.ci.conf.js"
    # - run: npm run webdriver-manager update -- --gecko false --standalone false --versions.chrome $(curl https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$(google-chrome --version | grep -iEo "[0-9]{1,3}" | head -n1))
    # - run: npm run webdriver-manager update -- --chrome false --standalone false
    # - run: npm run actions:e2e

  macos-setup-and-tests:
    runs-on: macos-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Setup upterm session
        uses: lhotari/action-upterm@v1
      - name: Use Node.js ${{ matrix.node-version }}
        run: |
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.1/install.sh | bash
          source ~/.bashrc

          sudo softwareupdate --install-rosetta --agree-to-license
          arch -x86_64 /bin/bash -c "nvm install 14 && nvm use 14"
      - run: npm install
      - run: npm update
      - run: npm run lint
      - run: npm run test
    # - run: npm test -- "--karma-config=./tests/karma.ci.conf.js" || npm test -- "--karma-config=./tests/karma.ci.conf.js"
    # retry tests once, in case they timed out on Mac OS
  windows-setup-and-tests:
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm update
      - run: npm run lint
      - run: npm run test
    # - run: npm test -- "--karma-config=./tests/karma.ci.conf.js"
